# Generated by Django 3.0.4 on 2020-03-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(default=None, null=True)),
                ('domain', models.CharField(max_length=253)),
                ('profile', models.CharField(max_length=255)),
                ('is_public', models.BooleanField()),
                ('task_id', models.CharField(max_length=255)),
            ],
        ),
    ]
